micronaut:
  application:
    name: desafiosMicronautKotlin
jackson:
  serialization:
    writeDatesAsTimestamps=false:

datasources:
  default:
    url: jdbc:postgresql://localhost:5434/desafios_mk
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
